services:
  # El servicio que correrá PHP
  app:
    build: .
    container_name: dmc_php_app
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
    working_dir: /var/www/html
    command: >
      sh -c "
        if [ ! -d 'vendor' ]; then
          echo 'Instalando dependencias de PHP...'
          composer install --no-dev --optimize-autoloader
        fi &&
        php-fpm
      "

  # El servicio del servidor web (Nginx)
  webserver:
    image: nginx:latest
    container_name: dmc_webserver
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # Servicio para el procesamiento de datos Python
  python-processor:
    image: python:3.11-slim
    container_name: dmc_python_processor
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "
        if [ ! -d 'venv' ]; then
          echo 'Creando entorno virtual de Python...'
          python -m venv venv
        fi &&
        echo 'Instalando dependencias de Python...' &&
        ./venv/bin/pip install numpy pandas scipy &&
        echo 'Ejecutando procesador de mapas...' &&
        ./venv/bin/python procesador_mapas.py &&
        echo 'Procesamiento completado. El contenedor se mantendrá en ejecución.' &&
        tail -f /dev/null
      "
    profiles:
      - tools

volumes:
  vendor: