<?php
/**
 * Plantilla principal (Layout) de la aplicación.
 * Este archivo envuelve todas las demás vistas.
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<!DOCTYPE html>
<html lang="es" class="h-100">
<head>
    <title>DMC - Monitor de Sequías</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <?= $this->headTitle('DMC - Monitor de Sequías')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Este bloque usa el helper headLink() para generar las etiquetas <link> con las rutas correctas -->
    <?= $this->headLink()
        // CSS de tu proyecto (deben estar en la carpeta public/)
        ->prependStylesheet($this->basePath('/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/js/leaflet/leaflet.css'))
        ->prependStylesheet($this->basePath('/css/climatologia.css'))
        ->prependStylesheet($this->basePath('/css/nuevo.css'))
        ->prependStylesheet($this->basePath('/css/megaNavBarBS5/megaNavBarBS5.css'))
        ->prependStylesheet($this->basePath('/css/font-awesome/css/font-awesome.min.css'));
        
    ?>

    <?= $this->headScript() ?>
</head>
<body class="d-flex flex-column h-100">

<header>
    <div class="d-flex justify-content-between">
        <div>
            <a href="https://climatologia.meteochile.gob.cl/images/logos/dmcNombre.png">
                <img class="img img-fluid" src="https://climatologia.meteochile.gob.cl/images/logos/dmcNombre.png" alt="Logo DMC">
            </a>
        </div>
        <div>
            <a href="https://www.dgac.gob.cl">
                <img class="img img-fluid" src="https://climatologia.meteochile.gob.cl/images/logos/dgac.png" alt="Logo DGAC">
            </a>
        </div>
    </div>
    <div class="row mb-0">
        <div class="col-12 mb-0">


            <nav class="navbar nav-climat navbar-expand-lg mb-2" data-show="fade" data-hide="fade" role="navigation">
                <a class="navbar-brand" href="/">
                    <i class="fa fa-home"></i>
                </a>

                <!-- Botón para colapsar el menú en pantallas pequeñas -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#MNBS5" aria-controls="MNBS5" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars navbar-toggler-icon" aria-hidden="true"></i>
                </button>

                <!-- MegaNavbar BS4 collapsible content  -->
                <div class="collapse navbar-collapse" id="MNBS5">
                    <ul class="navbar-nav mr-auto">
                        <!-- Cabezera del Menú frecuentes -->
                        <li class="nav-item dropdown line-vl">
                            <a class="nav-link dropdown-toggle" href="#idControl" id="dropdown01" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-star" aria-hidden="true"></i>
                                <strong> Frecuentes </strong>
                            </a>
                            <div class="dropdown-menu" id="idControl" aria-labelledby="dropdown01">
                                <!-- PRODUCTOD CONTROL -->
                                <div class="dropdown dropend">
                                    <h5 class="dropdown-header fs-6 fw-bold">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        Los más consultados
                                    </h5>
                                    <div class="dropdown-divider m-0"></div>
                                    <div class="aquiToy">
                                        <a class="dropdown-item" href="/application/requerimiento/producto/RE5029">
                                            <i class="wi wi-day-sunny" aria-hidden="true"></i> Visor EMA <br>
                                            <span class="small m-3"> Datos Estación Automática </span>
                                        </a>
                                    </div>
                                    <div class="aquiToy">
                                        <a class="dropdown-item" href="/application/requerimiento/producto/RE6006">
                                            <i class="fa fa-calendar-check-o" aria-hidden="true"></i> Estado Red Ema <br>
                                            <span class="small m-3"> Detalle de los mensajes más recientes </span>
                                        </a>
                                    </div>
                                    <div class="aquiToy">
                                        <a class="dropdown-item" href="/application/requerimiento/producto/RE5064">
                                            <i class="wi wi-night-alt-snow-wind" aria-hidden="true"></i> Meteograma <br>
                                            <span class="small m-3"> Datos Pronosticados a 5 días </span>
                                        </a>
                                    </div>
                                    <div class="aquiToy">
                                        <a class="dropdown-item" href="/application/requerimiento/producto/RE1024">
                                            <i class="wi wi-day-sunny" aria-hidden="true"></i> Olas de Calor <br>
                                            <span class="small m-3"> El monitoreo de olas de calor se actualiza diariamente a las 8 AM </span>
                                        </a>
                                    </div>
                                    <div class="aquiToy">
                                        <a class="dropdown-item" href="/application/requerimiento/producto/RE5063">
                                            <i class="wi wi-snowflake-cold" aria-hidden="true"></i> Olas de Frío <br>
                                            <span class="small m-3"> El monitoreo de olas de frío se actualiza diariamente a las 8 AM </span>
                                        </a>
                                    </div>
                                    <div class="aquiToy">
                                        <a class="dropdown-item" href="/application/requerimiento/producto/RE5008">
                                            <i class="fa fa-tag" aria-hidden="true"></i> Informe Climatológico diario <br>
                                            <span class="small m-3"> Informe diario para las estaciones nacionales </span>
                                        </a>
                                    </div>
                                    <div class="aquiToy">
                                        <a class="dropdown-item" href="/application/requerimiento/producto/RE8011">
                                            <i class="fa fa-cog" aria-hidden="true"></i> Web Services <br>
                                            <span class="small m-3"> Diferentes web-services para incluir nuestros datos en sus aplicaciones </span>
                                        </a>
                                    </div>
                                </div>



                            </div>
                        </li>

                        <!-- Cabezera del Menú de Control -->
                        <li class="nav-item dropdown line-vl">
                            <a class="nav-link dropdown-toggle" href="#idControl" id="dropdown01" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-check-square-o" aria-hidden="true"></i>
                                <strong> Control </strong>
                            </a>
                            <div class="dropdown-menu" id="idControl" aria-labelledby="dropdown01">
                                <div class="dropdown-header fs-6 fw-bold">
                                    <span>
                                        <i class="fa fa-check-square-o" aria-hidden="true"></i>
                                        Productos de Control
                                    </span>
                                </div>
                                <div class="dropdown-divider m-0"></div>
                                <!-- PRODUCTOD CONTROL -->
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#idControlDiario" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-plus-square-o" aria-hidden="true"></i> Diarios <span class="caret down right"></span>
                                        <br>
                                        <span class="small m-3 ">Controles a procesos diarios</span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="idControlDiario">
                                        <h5 class="dropdown-header fs-6 fw-bold">
                                            <i class="fa fa-check-square-o" aria-hidden="true"></i>
                                            Controles Diarios
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class="aquiToy">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6004">
                                                <i class="fa fa-plane" aria-hidden="true"></i> Observaciones Ingresadas Red Estaciones <br>
                                                <span class="small m-3"> Tiempo Real </span>
                                            </a>
                                        </div>
                                        <div class="aquiToy">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6014">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Control Ingreso Oportuno por Estación <br>
                                                <span class="small m-3"> Datos Ingresados por un operador </span>
                                            </a>
                                        </div>
                                        <div class="aquiToy">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6006">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Estado Actual Red EMA DGAC <br>
                                                <span class="small m-3"> Estaciones Automáticas </span>
                                            </a>
                                        </div>
                                        <div class="aquiToy">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6027">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Estado Red EMA NACIONAL <br>
                                                <span class="small m-3"> Estaciones Automáticas </span>
                                            </a>
                                        </div>
                                        <div class="aquiToy">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6024">
                                                <i class="fa fa-line-chart" aria-hidden="true"></i> Gráficos Recientes Red EMA <br>
                                                <span class="small m-3"> Gráficos últimos 60 días </span>
                                            </a>
                                        </div>
                                        <div class="aquiToy">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE7004">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Respaldo Diario <br>
                                                <span class="small m-3"> Bitácora de Respaldo diario de la DB </span>
                                            </a>
                                        </div>
                                        <div class="aquiToy">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6016">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Control Ingreso EMA a SACLIM <br>
                                                <span class="small m-3"> Datos de Estaciones Automáticas </span>
                                            </a>
                                        </div>
                                        <div class="aquiToy">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6021">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Control Datos Rechazados Estaciones Automáticas <br>
                                                <span class="small m-3"> Parámetro Malos en JSON </span>
                                            </a>
                                        </div>
                                        <!-- PRODUCTOD CONTROL -->
                                        <div class="dropdown dropendt">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#idControlDiarioMetar" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-plus-square-o" aria-hidden="true"></i> METAR <span class="caret down right"></span>
                                                <br>
                                                <span class="small m-3">Control de Calidad al mensaje METAR</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="idControlDiarioMetar">
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE6008">
                                                        <i class="fa fa-check-square-o" aria-hidden="true"></i> Control METAR Estación <br>
                                                        <span class="small m-3"> Saclim - AFTNDATA </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE6009">
                                                        <i class="fa fa-check-square-o" aria-hidden="true"></i> Control METAR Red Nacional <br>
                                                        <span class="small m-3"> Saclim - AFTNDATA </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- PRODUCTOD CONTROL -->
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#idControlMensual" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-plus-square-o" aria-hidden="true"></i> Mensual <span class="caret down right"></span>
                                        <br>
                                        <span class="small m-3">Controles a procesos mensuales</span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="idControlMensual">
                                        <h5 class="dropdown-header fs-6 fw-bold">
                                            <i class="fa fa-check-square-o" aria-hidden="true"></i>
                                            Controles Mensuales
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class=" ">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6015">
                                                <i class="fa fa-plane" aria-hidden="true"></i> Control de Ingreso Oportuno a SACLIM <br>
                                                <span class="small m-3"> Por un operador en la Estación </span>
                                            </a>
                                        </div>
                                        <div class=" ">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6012">
                                                <i class="fa fa-plane" aria-hidden="true"></i> Radio Sondas Ingresados <br>
                                                <span class="small m-3"> Vuelos del Mes </span>
                                            </a>
                                        </div>
                                        <div class=" ">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6013">
                                                <i class="fa fa-plane" aria-hidden="true"></i> Mensajes GTS de Buenos Aires <br>
                                                <span class="small m-3"> Control Mensajes Desde el GTS de Buenos Aires </span>
                                            </a>
                                        </div>
                                        <div class=" ">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6023">
                                                <i class="fa fa-envelope-o" aria-hidden="true"></i> Boletín Horario EMAS <br>
                                                <span class="small m-3"> Mensajes recibidos desde el GTS - BA </span>
                                            </a>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#idControlMensualEmas" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-plus-square-o" aria-hidden="true"></i> Estaciones Automáticas <span class="caret down right"></span>
                                                <br>
                                                <span class="small m-3">Datos Estaciones Automáticas</span>
                                            </a>
                                            <div class="dropdown-menu" id="idControlMensualEmas">
                                                <div class=" ">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE6018">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Datos EMAS a SACLIM <br>
                                                        <span class="small m-3"> Control de la información ingresada a SACLIM </span>
                                                    </a>
                                                </div>
                                                <div class=" ">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE6007">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Datos AMDAR Mensual <br>
                                                        <span class="small m-3"> Cantidad de Datos AMDAR Recibidos </span>
                                                    </a>
                                                </div>
                                                <div class=" ">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE6026">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Control Registro Diarios <br>
                                                        <span class="small m-3"> Detalle horario de datos presentes </span>
                                                    </a>
                                                </div>
                                                <div class=" ">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE6017">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Control Mensual datos llegados EMAS <br>
                                                        <span class="small m-3"> Use /DMC /FDF /INIA /DGA </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#idControlMensualMetar" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-plus-square-o" aria-hidden="true"></i> METAR <span class="caret down right"></span>
                                                <br>
                                                <span class="small m-3">Control de Calidad al mensaje METAR</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="idControlMensualMetar">
                                                <div class=" enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE6010">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Control METAR Estación <br>
                                                        <span class="small m-3"> Saclim - AFTNDATA </span>
                                                    </a>
                                                </div>
                                                <div class=" enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE6011">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Control METAR Red Estaciones <br>
                                                        <span class="small m-3"> Saclim - AFTNDATA </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- PRODUCTOD CONTROL -->
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#idControlCalidadDatos" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-plus-square-o" aria-hidden="true"></i> Control de Calidad <span class="caret down right"></span>
                                        <br>
                                        <span class="small m-3">Datos Ingresados a SACLIM</span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="idControlCalidadDatos">
                                        <h5 class="dropdown-header fs-6 fw-bold">
                                            <i class="fa fa-check-square-o" aria-hidden="true"></i>
                                            Controles de Calidad a Datos
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6020">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Completud de Datos <br>
                                                <span class="small m-3"> Completud del Programa de Observación </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6002">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Listado Estaciones con Errores <br>
                                                <span class="small m-3"> Estaciones que aún tienen errores </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6001">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Errores de la Estación <br>
                                                <span class="small m-3"> Errores pendiente de la estación </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6019">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Errores Recientes <br>
                                                <span class="small m-3"> Errores Recientes de la Red Básica </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6003">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Informe General <br>
                                                <span class="small m-3"> Total de Errores de Banco de Datos </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE6022">
                                                <i class="fa fa-check-square-o" aria-hidden="true"></i> Controles Definidos <br>
                                                <span class="small m-3"> Listado de los errores definidos en el sistema SACLIM </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <!-- Cabezera del Menú de Estaciones -->
                        <li class="nav-item dropdown line-vl">
                            <a class="nav-link dropdown-toggle" href="#idEstaciones" id="dropdown02" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-map-marker" aria-hidden="true"></i>
                                <strong> Estaciones </strong>
                            </a>
                            <div class="dropdown-menu" id="idEstaciones" aria-labelledby="dropdown02">
                                <!-- PRODUCTOD CONTROL -->
                                <h5 class="dropdown-header fs-6 fw-bold">
                                    <i class="fa fa-map-marker" aria-hidden="true"></i> Estaciones de la Red
                                </h5>
                                <div class="dropdown-divider m-0"></div>
                                <div class="">
                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE7003">
                                        <i class="fa fa-search-plus" aria-hidden="true"></i> Catastro de Estaciones Nacional <br>
                                        <span class="small m-3"> Buscador en base a criterios </span>
                                    </a>
                                </div>
                                <div class="">
                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE7001">
                                        <i class="fa fa-table" aria-hidden="true"></i> Listadode Estaciones por Región <br>
                                        <span class="small m-3"> Listado de estaciónes por región </span>
                                    </a>
                                </div>
                                <div class="">
                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE7012">
                                        <i class="fa fa-thumb-tack" aria-hidden="true"></i> Grupos de Estaciones <br>
                                        <span class="small m-3"> Conjunto de Estaciones definidos </span>
                                    </a>
                                </div>
                                <div class="">
                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE7002">
                                        <i class="fa fa-id-card-o" aria-hidden="true"></i> Ficha de la Estación <br>
                                        <span class="small m-3"> Metadatos de la estacion </span>
                                    </a>
                                </div>
                                <div class="">
                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE7011">
                                        <i class="fa fa-id-card-o" aria-hidden="true"></i> Estaciones en OSCAR <br>
                                        <span class="small m-3"> Estaciones Nacionales en OSCAR/Surface </span>
                                    </a>
                                </div>
                                <div class="">
                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE7008">
                                        <i class="fa fa-id-card-o" aria-hidden="true"></i> Elementos Definidos <br>
                                        <span class="small m-3"> Muestra todos los elemento definidos </span>
                                    </a>
                                </div>

                            </div>
                        </li>

                        <!-- Cabezera del Menú de Productos -->
                        <li class="nav-item dropdown line-vl">
                            <a class="nav-link dropdown-toggle" href="#idProductos" id="dropdown03" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-area-chart" aria-hidden="true"></i>
                                <strong> Productos </strong>
                            </a>
                            <div class="dropdown-menu " id="idProductos" aria-labelledby="dropdown03">
                                <div class="dropdown-header fs-6 fw-bold">
                                    <span>
                                        <i class="fa fa-area-chart" aria-hidden="true"></i>
                                        Productos Climáticos
                                    </span>
                                </div>
                                <div class="dropdown-divider m-0"></div>
                                <!-- PRODUCTOD DIARIOS -->
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#idDiarios" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-plus-square-o" aria-hidden="true"></i> Diarios <span class="caret down right"></span>
                                        <br>
                                        <span class="small m-3">Información de 1 día</span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="idDiarios">
                                        <h5 class="dropdown-header fs-6 fw-bold">
                                            <i class="fa fa-arrow-circle-o-down" aria-hidden="true"></i> Productos Diarios
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" href="#diariosMensajesCRT" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-plus-square-o" aria-hidden="true"></i> Mensajes Desde CRT <span class="caret down right"></span>
                                                <br>
                                                <span class="small m-3">Centro Regional De Telecomunicaciones</span>
                                            </a>

                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="diariosMensajesCRT">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="fa fa-check-square-o" aria-hidden="true"></i>
                                                    Mensajes Enviados desde
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5001">
                                                        <i class="fa fa-check-square-o" aria-hidden="true"></i> CRT de Brasil <br>
                                                        <span class="small m-3"> Centro Regional </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5002">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> CRT de Argentina <br>
                                                        <span class="small m-3"> Centro Regional </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" href="#diariosMensajesCodificados" id="dropdownLayouts" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-plus-square-o" aria-hidden="true"></i> Mensajes Codificados <span class="caret down right"></span>
                                                <br>
                                                <span class="small m-3">Centro Regional De Telecomunicaciones</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="diariosMensajesCodificados">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="fa fa-check-square-o" aria-hidden="true"></i>
                                                    Mensajes Codificados
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE6005">
                                                        <i class="fa fa-check-square-o" aria-hidden="true"></i> Mensajes SACLIM <br>
                                                        <span class="small m-3"> METAR y SINOP Codificados por SACLIM </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5004">
                                                        <i class="fa fa-check-square-o" aria-hidden="true"></i> Circular Metar <br>
                                                        <span class="small m-3"> Todas las estaciones para una hora </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5060">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Sinop BUFR <br>
                                                        <span class="small m-3"> DataFile para ClaveBUFR </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5005">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Circular Sinop <br>
                                                        <span class="small m-3"> Mensajes en clave SINOP </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#diariosRadiacionSolar" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-day-sunny" aria-hidden="true"></i> Radiación Solar <span class="caret down right"></span>
                                                <br>
                                                <span class="small m-3">Radiacion UVB y Global</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="diariosRadiacionSolar">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-day-sunny" aria-hidden="true"></i> Radiacion UVB y Global
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5010">
                                                        <i class="wi wi-hot" aria-hidden="true"></i> Índice Radiación UVB Estación <br>
                                                        <span class="small m-3"> Mediciones Horarias y Máximo del día </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5019">
                                                        <i class="wi wi-hot" aria-hidden="true"></i> Índice Radiación IUV Máximo diario <br>
                                                        <span class="small m-3"> Red Nacional de Monitoreo </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5020">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Índice Radiación IUV 10 Días Previos <br>
                                                        <span class="small m-3"> Valores horarios y máximo diario </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5026">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Radiación Global Diaria <br>
                                                        <span class="small m-3"> Radiación Instantánea datos cada 10 minutos </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#diariosDatosDeAltura" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-wifi" aria-hidden="true"></i> Información de Altura <span class="caret down right"></span>
                                                <br>
                                                <span class="small m-3">RadioSondas y Datos AMDAR</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="diariosDatosDeAltura">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="fa fa-bookmark-o" aria-hidden="true"></i> Información de Altura
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5014">
                                                        <i class="wi wi-small-craft-advisory" aria-hidden="true"></i> Diagrama SkewTLogP <br>
                                                        <span class="small m-3"> Datos del Vuelo de Radio Sonda </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5030">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Vuelos Diarios AMDAR <br>
                                                        <span class="small m-3"> Aeronave que enviaron datos AMDAR </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5032">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Datos AMDAR por zona <br>
                                                        <span class="small m-3"> A 50 Kilómetros de distancia de la Estación </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5016">
                                                        <i class="wi wi-thermometer-exterior" aria-hidden="true"></i> Temperatura Cercanos a la Isoterma Cero <br>
                                                        <span class="small m-3"> Información enviada por aeronaves AMDAR </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5017">
                                                        <i class="wi wi-thermometer" aria-hidden="true"></i> Perfil AMDAR <br>
                                                        <span class="small m-3"> Temperatura y Viento </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5061">
                                                        <i class="fa fa-bar-chart" aria-hidden="true"></i> Señales de Retrodispersión <br>
                                                        <span class="small m-3"> Nefobasímetro </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#diariosSatelite" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-sliders" aria-hidden="true"></i> Productos Satelitales <span class="caret down right"></span>
                                                <br>
                                                <span class="small m-3">Datos Actuales </span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="diariosSatelite">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="fa fa-rocket" aria-hidden="true"></i>
                                                    Productos Satelitales
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5067">
                                                        <i class="wi wi-night-thunderstorm" aria-hidden="true"></i> Imágenes de Tormentas <br>
                                                        <span class="small m-3"> Mes solicitado e Imágenes Recientes </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5070">
                                                        <i class="fa fa-globe" aria-hidden="true"></i> Imágenes Satelíticas <br>
                                                        <span class="small m-3"> Colección Imágenes Satelitales </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#diariosPronosticados" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-sliders" aria-hidden="true"></i> Datos de Modelos <span class="caret down right"></span>
                                                <br>
                                                <span class="small m-3">Datos Pronosticados por Modelo </span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="diariosPronosticados">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="fa fa-sliders" aria-hidden="true"></i>
                                                    Datos Modelo WRF
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5062">
                                                        <i class="fa  fa-line-chart" aria-hidden="true"></i> Gráficos Comparativos <br>
                                                        <span class="small m-3"> Datos Modelados/Observados </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5065">
                                                        <i class="wi wi-snowflake-cold" aria-hidden="true"></i> Pronóstico Heladas <br>
                                                        <span class="small m-3"> Imágenes Heladas Blancas/Negras </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5064">
                                                        <i class="fa fa-bar-chart" aria-hidden="true"></i> Meteograma WRF a 5 días <br>
                                                        <span class="small m-3"> Pronóstico gráfico interactivo </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#diariosRuta" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-small-craft-advisory" aria-hidden="true"></i> Hoja de Ruta <span class="caret down right"></span>
                                                <br>
                                                <span class="small m-3">Diagrama estado de la estación</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="diariosRuta">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-small-craft-advisory" aria-hidden="true"></i> Hoja de Ruta
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5012">
                                                        <i class="wi wi-thermometer-exterior" aria-hidden="true"></i> Hoja de Ruta Nacional <br>
                                                        <span class="small m-3"> Representación gráfica de datos </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5013">
                                                        <i class="wi wi-thermometer" aria-hidden="true"></i> Hoja de Ruta de la Estación <br>
                                                        <span class="small m-3"> Representación gráfica de datos 10 días recientes </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#diariosBoletines" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-day-sunny-overcast" aria-hidden="true"></i> Boletines Diarios <span class="caret down right"></span>
                                                <br>
                                                <span class="small m-3">Climatológicos y AgroMeteorológicos</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="diariosBoletines">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="fa fa-bookmark-o" aria-hidden="true"></i> Boletines Diarios
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5051">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Boletín Regional Diario 08:00 Hrs. <br>
                                                        <span class="small m-3"> Boletín Regional diario con fines Agro-Meteorológicos </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5052">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Boletín Regional Diario 14:00 Hrs. <br>
                                                        <span class="small m-3"> Boletín Regional diario con fines Agro-Meteorológicos </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5024">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Monitoreo Diario de Heladas Recientes <br>
                                                        <span class="small m-3"> Red Nacional de Monitoreo </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5007">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Informe Climatológico Diario <br>
                                                        <span class="small m-3"> Totales y normales para la estación </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE5008">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Informe Climatológico Diario Nacional <br>
                                                        <span class="small m-3"> Totales y normales para un conjunto de estaciones </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div>
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE1033">
                                                <i class="fa fa-map" aria-hidden="true"></i> Cartas de Superficie
                                                <br>
                                                <span class="small m-3"> Archivo Digital Cartas de Superficie</span>
                                            </a>
                                        </div>
                                    </div>
                                </div><!-- PRODUCTOD MENSUALES -->
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#idMensuales" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-plus-square-o" aria-hidden="true"></i> Mensuales <span class="caret down right"></span>
                                        <br>
                                        <span class="small m-3">Información de 1 mes</span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="idMensuales">
                                        <h5 class="dropdown-header fs-6 fw-bold">
                                            <i class="fa fa-arrow-circle-o-down" aria-hidden="true"></i> Productos Mensuales
                                        </h5>

                                        <div class="dropdown-divider m-0"></div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#mensualPrecipitacion" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-umbrella" aria-hidden="true"></i>
                                                Precipitación y Cielo Cubierto
                                                <br>
                                                <span class="small m-3">Líquida y Sólida</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="mensualPrecipitacion">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-rain" aria-hidden="true"></i>
                                                    Precipitación
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1006">
                                                        <i class="wi wi-rain" aria-hidden="true"></i> Agua Caída Diaria <br>
                                                        <span class="small m-3"> Total diario,mensual y valores extremos </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1014">
                                                        <i class="wi wi-snow" aria-hidden="true"></i> Nieve Fresca Diaria <br>
                                                        <span class="small m-3"> Mediciones de altura de la nieve fresca </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1032">
                                                        <i class="wi wi-rain" aria-hidden="true"></i> Mensual Comparativo de Precipitación <br>
                                                        <span class="small m-3"> Informe comparativo de agua medida y agua obtenida de la digitalización de los pluviógrafos. </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1007">
                                                        <i class="wi wi-cloudy" aria-hidden="true"></i> Cielo Cubierto <br>
                                                        <span class="small m-3"> Total diario, mensual y valores extremos </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1034">
                                                        <i class="wi wi-rain" aria-hidden="true"></i> Informe de Agua Caída Reciente <br>
                                                        <span class="small m-3"> Totales acumulados diarios recientes </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#mensualTemperatura" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-thermometer" aria-hidden="true"></i>
                                                Temperatura
                                                <br>
                                                <span class="small m-3">Media, máxima y mínima</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="mensualTemperatura">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-thermometer" aria-hidden="true"></i>
                                                    Temperatura
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1005">
                                                        <i class="wi wi-thermometer" aria-hidden="true"></i> Informe Mensual de Temperatura <br>
                                                        <span class="small m-3"> Media diaria, extremas y mensual en °C </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1021">
                                                        <i class="fa fa-thermometer-empty" aria-hidden="true"></i> Temperatura Grados Días Mensual <br>
                                                        <span class="small m-3"> Acomulación de Grados días (base 5 a 12 ) </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1024">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Monitoreo Olas de Calor <br>
                                                        <span class="small m-3"> Últimos 90 días </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1031">
                                                        <i class="wi wi-night-snow-wind" aria-hidden="true"></i> Monitoreo Olas de Frío <br>
                                                        <span class="small m-3"> Últimos 90 días </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1025">
                                                        <i class="fa fa-pencil" aria-hidden="true"></i> Temperatura Media Diaria <br>
                                                        <span class="small m-3"> Diferentes métodos de obtención </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#mensualViento" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-small-craft-advisory" aria-hidden="true"></i>
                                                Viento
                                                <br>
                                                <span class="small m-3">Dirección e Intensidad a 10 Metros</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="mensualViento">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-small-craft-advisory" aria-hidden="true"></i>
                                                    Viento de Superficie
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1008">
                                                        <i class="wi wi-small-craft-advisory" aria-hidden="true"></i> Viento Predominante <br>
                                                        <span class="small m-3"> Tabla de frecuencia para 8 direcciones </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1009">
                                                        <i class="wi wi-small-craft-advisory" aria-hidden="true"></i> Viento Predominante <br>
                                                        <span class="small m-3"> Tabla de frecuencia para 16 direcciones </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#mensualMonitor" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-small-craft-advisory" aria-hidden="true"></i>
                                                Monitor de Sequía
                                                <br>
                                                <span class="small m-3">Productos plataforma CASTEHR</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="mensualMonitor">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-day-sunny" aria-hidden="true"></i>
                                                    Monitor de Sequía
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1029">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Mapa Intensidad de Sequía <br>
                                                        <span class="small m-3"> Actual y pronosticado </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1030">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Monitor de Sequía de Chile <br>
                                                        <span class="small m-3"> Porcentaje de Afectación Anual </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#mensualRadiacion" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-day-sunny" aria-hidden="true"></i>
                                                Radiación Solar
                                                <br>
                                                <span class="small m-3">Globla,UVB y Horas de Sol</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="mensualRadiacion">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-hot" aria-hidden="true"></i>
                                                    Radiación Solar
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1010">
                                                        <i class="fa fa-umbrella" aria-hidden="true"></i> Índice Radiación UVB <br>
                                                        <span class="small m-3"> Total diario,mensual y valores extremos </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1019">
                                                        <i class="wi wi-hot" aria-hidden="true"></i> Radiacion Global Instantánea <br>
                                                        <span class="small m-3"> Promedios y Máximos Horarios </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1020">
                                                        <i class="wi wi-hot" aria-hidden="true"></i> Radiacion Global Acumulada <br>
                                                        <span class="small m-3"> Promedios y Máximos Horarios </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1011">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Horas De Sol (Fomet 031) <br>
                                                        <span class="small m-3"> Horas de Sol horaria, diaria, mensual y valores totales </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#mensualPresion" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-barometer" aria-hidden="true"></i>
                                                Presión Atmosférica y Humedad
                                                <br>
                                                <span class="small m-3">Nivel estación, mar, estándar </span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="mensualPresion">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-barometer" aria-hidden="true"></i>
                                                    Presión Atmosférica
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1001">
                                                        <i class="fa fa-thumb-tack" aria-hidden="true"></i> Nivel de la Estación <br>
                                                        <span class="small m-3"> Valores medios diarias y mensuales </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1002">
                                                        <i class="wi wi-flood" aria-hidden="true"></i> Nivel del Mar <br>
                                                        <span class="small m-3"> Valores medios diarias y mensuales </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1003">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Nivel Estandar <br>
                                                        <span class="small m-3"> Valores medios diarias y mensuales </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1004">
                                                        <i class="wi wi-humidity" aria-hidden="true"></i> Humedad relativa del Aire <br>
                                                        <span class="small m-3"> Media diaria y mensual en Porcentaje </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#mensualClimatologico" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-file-text-o" aria-hidden="true"></i>
                                                Informes Climatológicos
                                                <br>
                                                <span class="small m-3">Promedios, Totales y Extremos</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="mensualClimatologico">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="fa fa-file-text-o" aria-hidden="true"></i>
                                                    Informes Climatológicos
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1018">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Mensual datos Diarios <br>
                                                        <span class="small m-3"> Valores medios, acumulados y extremos </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1016">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Sólo Datos Mensuales <br>
                                                        <span class="small m-3"> Valores medios, acumulados y extremos </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1012">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Regional Decadal <br>
                                                        <span class="small m-3"> Valores medios, acumulados y extremos </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1013">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Temperatura y Precipitación <br>
                                                        <span class="small m-3"> Promedios y totales Mensuales para toda la Red </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1015">
                                                        <i class="fa fa-comment-o" aria-hidden="true"></i> Niveles Mandatorios RadioSonda <br>
                                                        <span class="small m-3"> Promedios niveles mandatorios </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1022">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Hoja Mensual de Datos <br>
                                                        <span class="small m-3"> Datos horarias de algunos elementos </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1026">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Climat Mensual DataFile BUFR <br>
                                                        <span class="small m-3"> Descriptores y datos de la Plantilla TM307073 </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1027">
                                                        <i class="fa fa-file-text-o" aria-hidden="true"></i> Climat Mensual DataFile BUFR <br>
                                                        <span class="small m-3"> Descriptores y datos de la Plantilla TM307074 </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- PRODUCTOD ANUALES -->
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#idAnual" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-plus-square-o" aria-hidden="true"></i> Anuales <span class="caret down right"></span>
                                        <br>
                                        <span class="small m-3">Información de 1 año</span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="idAnual">
                                        <h5 class="dropdown-header fs-6 fw-bold">
                                            <i class="fa fa-arrow-circle-o-down" aria-hidden="true"></i> Productos Anuales
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#anualAnuario" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-earthquake" aria-hidden="true"></i>
                                                Anuarios
                                                <br>
                                                <span class="small m-3">Valores mensuales y anuales </span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="anualAnuario">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-earthquake" aria-hidden="true"></i>
                                                    Anuarios
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2020">
                                                        <i class="wi wi-earthquake" aria-hidden="true"></i> Anuario Climatológico <br>
                                                        <span class="small m-3"> Valores mensuales y anuales </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2021">
                                                        <i class="fa fa-comment-o" aria-hidden="true"></i> Anuario Datos de Altura <br>
                                                        <span class="small m-3"> Valores mensuales y anuales </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#anualPrecipitacion" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-umbrella" aria-hidden="true"></i>
                                                Precipitación y Cielo Cubierto
                                                <br>
                                                <span class="small m-3">Líquida y Sólida</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="anualPrecipitacion">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-umbrella" aria-hidden="true"></i>
                                                    Precipitación
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2009">
                                                        <i class="wi wi-rain" aria-hidden="true"></i> Agua Caída Diaria <br>
                                                        <span class="small m-3"> Total diario,mensual, anual y valores extremos </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2014">
                                                        <i class="wi wi-snow" aria-hidden="true"></i> Nieve Fresca Diaria <br>
                                                        <span class="small m-3"> Mediciones de altura de la nieve fresca </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2008">
                                                        <i class="wi wi-cloudy" aria-hidden="true"></i> Cielo Cubierto <br>
                                                        <span class="small m-3"> Total diario, mensual, anual y valores extremos </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#anualTemperaturar" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-thermometer" aria-hidden="true"></i>
                                                Temperatura
                                                <br>
                                                <span class="small m-3">Media, máxima y mínima</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="anualTemperaturar">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-thermometer" aria-hidden="true"></i>
                                                    Anuario de Temperatura
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2005">
                                                        <i class="wi wi-thermometer" aria-hidden="true"></i> Anuario Temperatura Media <br>
                                                        <span class="small m-3"> Valores diarios, mensuales y extremos para un año </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2006">
                                                        <i class="wi wi-thermometer-exterior" aria-hidden="true"></i> Anuario Temperatura Mínima <br>
                                                        <span class="small m-3"> Valores diarios,mensuales y extremos para un año </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2007">
                                                        <i class="wi wi-thermometer" aria-hidden="true"></i> Anuario Temperatura Máxima <br>
                                                        <span class="small m-3"> Valores diarios,mensuales y extremos para un año </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2023">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Ola De Calor Diurna <br>
                                                        <span class="small m-3"> Resumen Anual de las Olas de Calor de la Estación </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2025">
                                                        <i class="fa fa-snowflake-o" aria-hidden="true"></i> Ola De Frio Anual <br>
                                                        <span class="small m-3"> Resumen Anual de las Olas de Frio de la Estación </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2017">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Grados Días Anual <br>
                                                        <span class="small m-3"> Acumulación de Grados días (base 5 a 12 ) </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2024">
                                                        <i class="wi wi-thermometer-exterior" aria-hidden="true"></i> Heladas <br>
                                                        <span class="small m-3"> Monitoréo Anual de Heladas </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2018">
                                                        <i class="wi wi-thermometer-exterior" aria-hidden="true"></i> Horas de Frío <br>
                                                        <span class="small m-3"> Acumulación de horas por debajo de 7ºC </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropright">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#anualViento" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-small-craft-advisory" aria-hidden="true"></i>
                                                Viento
                                                <br>
                                                <span class="small m-3">Dirección e Intensidad a 10 Metros</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="anualViento">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-small-craft-advisory" aria-hidden="true"></i>
                                                    Viento de Superficie
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2012">
                                                        <i class="wi wi-small-craft-advisory" aria-hidden="true"></i> Viento Predominante Anual <br>
                                                        <span class="small m-3"> Tabla de frecuencia para 8 direcciones </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2013">
                                                        <i class="wi wi-small-craft-advisory" aria-hidden="true"></i> Viento Predominante Anual <br>
                                                        <span class="small m-3"> Tabla de frecuencia para 16 direcciones </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#anualRadiacion" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-day-sunny" aria-hidden="true"></i>
                                                Radiación Solar
                                                <br>
                                                <span class="small m-3">Globla,UVB y Horas de Sol</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="anualRadiacion">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-day-sunny" aria-hidden="true"></i>
                                                    Radiación Solar
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2011">
                                                        <i class="fa fa-umbrella" aria-hidden="true"></i> Índice Radiación UVB <br>
                                                        <span class="small m-3"> Total diario,mensual, anual y extremos </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2015">
                                                        <i class="wi wi-hot" aria-hidden="true"></i> Radiacion Global Instantánea <br>
                                                        <span class="small m-3"> Promedios y Máximos Horarios </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2016">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Radiación Global Acumulada Anual <br>
                                                        <span class="small m-3"> Valores diario, Mensual y Anual </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2010">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Anuario Horas De Sol <br>
                                                        <span class="small m-3"> Valores diarios,mensuales y totales anuales </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropright">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#anualPresion" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-barometer" aria-hidden="true"></i>
                                                Presión Atmosférica y Humedad
                                                <br>
                                                <span class="small m-3">Nivel estación, mar, estándar </span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="anualPresion">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-barometer" aria-hidden="true"></i>
                                                    Presión Atmosférica
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2001">
                                                        <i class="fa fa-thumb-tack" aria-hidden="true"></i> Nivel de la Estación <br>
                                                        <span class="small m-3"> Medias diarias, mensuales y anuales </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2002">
                                                        <i class="wi wi-flood" aria-hidden="true"></i> Nivel del Mar <br>
                                                        <span class="small m-3"> Medias diarias, mensuales y anuales </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2003">
                                                        <i class="fa fa-plane" aria-hidden="true"></i> Nivel Estandar <br>
                                                        <span class="small m-3"> Medias diarias, mensuales y anuales </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2004">
                                                        <i class="wi wi-humidity" aria-hidden="true"></i> Humedad relativa del Aire <br>
                                                        <span class="small m-3"> Media diaria y mensual en Porcentaje </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE2022">
                                                        <i class="wi wi-humidity" aria-hidden="true"></i> Anuario de Evapotranspiración <br>
                                                        <span class="small m-3"> Totales y Promedios Mensuales y Anual </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!-- PRODUCTOD MENSUALES -->
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#idHistoricos" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-hourglass-end" aria-hidden="true"></i> Historicos <span class="caret down right"></span>
                                        <br>
                                        <span class="small m-3">Información de Varios Años </span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="idHistoricos">
                                        <h5 class="dropdown-header fs-6 fw-bold">
                                            <i class="fa fa-hourglass-end" aria-hidden="true"></i> Productos Históricos
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#historicoTemperatura" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-thermometer" aria-hidden="true"></i>
                                                Temperatura
                                                <br>
                                                <span class="small m-3">Media, máxima y mínima</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="historicoTemperatura">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-thermometer" aria-hidden="true"></i>
                                                    Temperatura
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3002">
                                                        <i class="wi wi-thermometer" aria-hidden="true"></i> Temperatura Mensual Histórica <br>
                                                        <span class="small m-3"> Todos los datos disponibles para el mes solicitado en °C </span>
                                                    </a>
                                                </div>
                                                <div class="enabled">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3023">
                                                        <i class="wi wi-thermometer" aria-hidden="true"></i> Temperatura Histórica 30 Años <br>
                                                        <span class="small m-3"> Temperaturas Medias y Extremas en 30 Años </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3003">
                                                        <i class="wi wi-thermometer" aria-hidden="true"></i> Temperatura Anual Histórica <br>
                                                        <span class="small m-3"> Media, Máxima y Mínima de la Estación en °C </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3001">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Olas de Calor <br>
                                                        <span class="small m-3"> Eventos de Olas de Calor de la Estación °C </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3010">
                                                        <i class=" fa fa-snowflake-o" aria-hidden="true"></i> Olas de Frio <br>
                                                        <span class="small m-3"> Eventos de Olas de Frio de la Estación °C </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3004">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Umbrales de Olas de Calor <br>
                                                        <span class="small m-3"> Valor de los umbrales de las olas de calor </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3009">
                                                        <i class="fa fa-snowflake-o" aria-hidden="true"></i> Umbrales de Olas de Frio <br>
                                                        <span class="small m-3"> Valor de los umbrales de las olas de frio </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#mensualPrecipitacion" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-umbrella" aria-hidden="true"></i>
                                                Precipitación
                                                <br>
                                                <span class="small m-3">Líquida y Sólida</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="mensualPrecipitacion">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-umbrella" aria-hidden="true"></i>
                                                    Precipitación
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3005">
                                                        <i class="wi wi-rain" aria-hidden="true"></i> Histórica Mensual <br>
                                                        <span class="small m-3"> Totales mensuales en (mm) </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3007">
                                                        <i class="wi wi-rain" aria-hidden="true"></i> Valores de Quintiles Mensual <br>
                                                        <span class="small m-3"> Quintiles mensuales en (mm) </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#cambioPrecipitacion" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-umbrella" aria-hidden="true"></i>
                                                Cambio Climático
                                                <br>
                                                <span class="small m-3">Índices y mapas </span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="cambioPrecipitacion">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-umbrella" aria-hidden="true"></i>
                                                    Cambio Climatico
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3016">
                                                        <i class="wi wi-rain" aria-hidden="true"></i> Índices Climáticos y Tendencia <br>
                                                        <span class="small m-3"> Gráfico y Tendencia para la Estación </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3015">
                                                        <i class="fa fa-map-o" aria-hidden="true"></i> Mapa Índices Climáticos <br>
                                                        <span class="small m-3"> Deferentes Índices Definidos </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#historicoMonitor" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-small-craft-advisory" aria-hidden="true"></i>
                                                Monitor de Sequía
                                                <br>
                                                <span class="small m-3">Productos plataforma CASTEHR</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="historicoMonitor">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-small-craft-advisory" aria-hidden="true"></i>
                                                    Monitor de Sequía
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3024">
                                                        <i class="wi wi-day-sunny" aria-hidden="true"></i> Área Afectación Sequía <br>
                                                        <span class="small m-3"> Actual y pronosticado </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#descargaDatos" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-book" aria-hidden="true"></i>
                                                Normales y Descargas
                                                <br>
                                                <span class="small m-3">Series de datos Completas</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="descargaDatos">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="fa fa-book" aria-hidden="true"></i>
                                                    Normales y Descargas
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE1017">
                                                        <i class="fa fa-download" aria-hidden="true"></i> Datos AMDAR <br>
                                                        <span class="small m-3"> Datos Mensuales AMDAR </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3008">
                                                        <i class="fa fa-download" aria-hidden="true"></i> Datos SACLIM <br>
                                                        <span class="small m-3"> Series de datos completos </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE8011">
                                                        <i class="fa fa-download" aria-hidden="true"></i> Recursos Web Json <br>
                                                        <span class="small m-3"> Datos Json para consumir por aplicaciones </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3017">
                                                        <i class="fa fa-download" aria-hidden="true"></i> Datos Estación Automática <br>
                                                        <span class="small m-3"> Datos minutarios Mensuales </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3026">
                                                        <i class="fa fa-download" aria-hidden="true"></i> Datos Ozono <br>
                                                        <span class="small m-3"> Datos vuelos ozono sonda de Isla de Pascua </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3006">
                                                        <i class="fa fa-book" aria-hidden="true"></i> Datos Normales y Promedios <br>
                                                        <span class="small m-3"> Promedios históricos de 30 años o menos </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown dropend">
                                            <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#historicoFormularios" aria-haspopup="true" aria-expanded="false">
                                                <i class="wi wi-thermometer" aria-hidden="true"></i>
                                                Formularios - Diagramas
                                                <br>
                                                <span class="small m-3">Documentos Digitalizados</span>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="historicoFormularios">
                                                <h5 class="dropdown-header fs-6 fw-bold">
                                                    <i class="wi wi-thermometer" aria-hidden="true"></i>
                                                    Formularios - Archivo Nacional
                                                </h5>
                                                <div class="dropdown-divider m-0"></div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3019">
                                                        <i class="fa fa-book" aria-hidden="true"></i> Fomet0024 <br>
                                                        <span class="small m-3"> Registro de Observaciones horarias </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3018">
                                                        <i class="fa fa-book" aria-hidden="true"></i> Fomet0029 <br>
                                                        <span class="small m-3"> Registro de Observaciones diarias </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3021">
                                                        <i class="fa fa-book" aria-hidden="true"></i> Pluviogramas <br>
                                                        <span class="small m-3"> Registro semanal de Agua caída </span>
                                                    </a>
                                                </div>
                                                <div class="">
                                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE3020">
                                                        <i class="fa fa-book" aria-hidden="true"></i> Cartas Superficie <br>
                                                        <span class="small m-3"> Carta Sinóptica de superficie nacional </span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="dropdown-divider m-0"></div>
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#diariosEmas" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-podcast" aria-hidden="true"></i> Estaciones Automáticas <span class="caret down right"></span>
                                        <br>
                                        <span class="small m-3">Red DGAC - DMC</span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="diariosEmas">
                                        <h5 class="dropdown-header fs-6 fw-bold">
                                            <i class="fa fa-podcast" aria-hidden="true"></i> Estaciones Automáticas
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class="titulo">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE5029">
                                                <i class="fa fa-file-text-o" aria-hidden="true"></i> Visor de Datos EMA <br>
                                                <span class="small m-3"> Principales parámetro medidos por la estación </span>
                                            </a>
                                        </div>
                                        <div class="titulo">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE5021">
                                                <i class="fa fa-file-text-o" aria-hidden="true"></i> Visor Precipitación EMA <br>
                                                <span class="small m-3"> Red de Estaciones Automática de la Red Básica Climatológica </span>
                                            </a>
                                        </div>
                                        <div class="titulo">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE5028">
                                                <i class="fa fa-file-text-o" aria-hidden="true"></i> Gráficos Recientes <br>
                                                <span class="small m-3"> Gráficos para diferentes parámetros de la Estación Automática </span>
                                            </a>
                                        </div>
                                        <div class="titulo">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE5023">
                                                <i class="fa fa-file-text-o" aria-hidden="true"></i> Informe Diario Red EMA <br>
                                                <span class="small m-3"> Informe diario de Temperatura y Precipitación </span>
                                            </a>
                                        </div>
                                        <div class="titulo">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE5006">
                                                <i class="fa fa-file-text-o" aria-hidden="true"></i> Datos Estación Automática <br>
                                                <span class="small m-3"> Datos minutarios de la estación automática </span>
                                            </a>
                                        </div>
                                        <div class="titulo">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE5027">
                                                <i class="fa fa-file-text-o" aria-hidden="true"></i> Datos Horarios Estación EMA <br>
                                                <span class="small m-3"> Información de 48 horas anteriores </span>
                                            </a>
                                        </div>
                                        <div class="titulo">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE5015">
                                                <i class="fa fa-file-text-o" aria-hidden="true"></i> Boletín Pluviométrico Regional DGA-DMC-INIA <br>
                                                <span class="small m-3"> Red Nacional de Estaciones Automáticas </span>
                                            </a>
                                        </div>
                                        <div class="titulo">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE5022">
                                                <i class="fa fa-file-text-o" aria-hidden="true"></i> Boletín Temperaturas Regional DGA-DMC-INIA <br>
                                                <span class="small m-3"> Red Nacional de Estaciones Automáticas </span>
                                            </a>
                                        </div>
                                        <div class="titulo">
                                            <a class="dropdown-item" href="/application/requerimiento/producto/RE5056">
                                                <i class="wi wi-day-sunny-overcast" aria-hidden="true"></i> Mapa Red Estaciones Automáticas Nacional <br>
                                                <span class="small m-3"> Estaciones DGAC-INIA-FDF </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <!-- Cabezera del Menú de Publicaciones -->
                        <li class="nav-item dropdown line-vl">
                            <a class="nav-link dropdown-toggle" href="#idPublicaciones" id="dropdown04" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
                                <strong> Publicaciones </strong>
                            </a>
                            <div class="dropdown-menu" id="idPublicaciones" aria-labelledby="dropdown04">
                                <div class="dropdown-header fs-6 fw-bold">
                                    <span>
                                        <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Publicaciones Climatológicas
                                    </span>
                                </div>
                                <div class="dropdown-divider m-0"></div>
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle spacingTxt" data-bs-toggle="dropdown" id="dropdownLayouts" href="#publicacionesAnuales" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-plus-square-o" aria-hidden="true"></i> Publicaciones Anuales
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="publicacionesAnuales">
                                        <h5 class="dropdown-header">
                                            Anuarios
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/anuario">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Anuario Climatológico <br>
                                                <span class="small m-3"> Promedios mensuales y anuales </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/reporteClimatologico">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Reporte Climatológico Anual <br>
                                                <span class="small m-3"> Condiciones climáticas del año </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/boletinEventosExtremos">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Boletín Anual Eventos Extremos <br>
                                                <span class="small m-3"> Recopilación de eventos extremos del año </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/boletinAnualOzono">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Boletín Ozono y Radiación <br>
                                                <span class="small m-3"> Ozono estratosférico y radiación ultravioleta </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" aria-haspopup="true" href="#publicacionesSemestrales" aria-expanded="false">
                                        <i class="fa fa-plus-square-o" aria-hidden="true"></i>
                                        Publicaciones Semestrales
                                        <span class="caret down right"></span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="publicacionesSemestrales">
                                        <h5 class="dropdown-header">
                                            Semestrales
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/boletinSolarimetricoSemestral">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Informe Solarimétrico <br>
                                                <span class="small m-3"> Informe semestral de radiación global </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#publicacionesMensuales" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-plus-square-o" aria-hidden="true"></i> Publicaciones Mensuales
                                        <span class="caret down right"></span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="publicacionesMensuales">
                                        <h5 class="dropdown-header">
                                            Mensuales
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/boletinClimatologicoMensual">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Boletín Climatológico Mensual <br>
                                                <span class="small m-3"> Visión general del comportamiento climático del mes </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicacionesb/boletinAgroclimatico">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Boletín Agroclimático Mensual <br>
                                                <span class="small m-3"> Perspectiva Agroclimática Estacional </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/boletinAntarticoMensual">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Boletín Antártico Mensual <br>
                                                <span class="small m-3"> Describe las condiciones climáticas del territorio antártico chileno </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/boletinMonitoreoOzonoMensual">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Boletín Monitoreo Ozono <br>
                                                <span class="small m-3"> Monitorea el desarrollo del agujero de ozono </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/boletinDeSequias">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Boletín Mensual de Sequías <br>
                                                <span class="small m-3"> Monitorea de las sequías </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/boletinTendenciasClimaticas">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Boletín Tendencias Climáticas <br>
                                                <span class="small m-3"> Tendencias climáticas para los próximos 3 meses </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#publicacionesEspeciales" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-plus-square-o" aria-hidden="true"></i> Publicaciones Especiales <span class="caret down right"></span>
                                        <span class="caret down right"></span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="publicacionesEspeciales">
                                        <h5 class="dropdown-header">
                                            Especiales
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/boletinClimaHoy">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> El Clima Hoy <br>
                                                <span class="small m-3"> Publicación que resume las condiciones climáticas más recientes </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/climatologias">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Climatologías <br>
                                                <span class="small m-3"> Climatologías General </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="dropdown dropend">
                                    <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" id="dropdownLayouts" href="#publicacionesCambioClimatico" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-plus-square-o" aria-hidden="true"></i> Publicaciones Cambio Climático
                                        <span class="caret down right"></span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownLayouts" id="publicacionesCambioClimatico">
                                        <h5 class="dropdown-header">
                                            Cambio Climático
                                        </h5>
                                        <div class="dropdown-divider m-0"></div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/notasCambioClimatico">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Notas Especiales <br>
                                                <span class="small m-3"> Resumenes e informes de interés </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/reporteEvolucionClima">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Reporte Anual Evolución del Clima <br>
                                                <span class="small m-3"> Publicación de Cambio Climático en Chile </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicaciones/climaticoAeronautico">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Cambio Climático y la Aeronáutica <br>
                                                <span class="small m-3"> Impacto del cambio climático en los FIRS </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicacionesb/indiceCambioClimatico">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Índices de Cambio Climático <br>
                                                <span class="small m-3"> Información sobre índice de Cambio Climático </span>
                                            </a>
                                        </div>
                                        <div class="">
                                            <a class="dropdown-item" href="/application/publicacionesb/isotermaCero">
                                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i> Climatología y tendencia de la Altura de la isoterma 0°C <br>
                                                <span class="small m-3"> Altura de la Isoterma 0°C </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </li>

                        <!-- Cabezera del Menú de Acerca -->
                        <li class="nav-item dropdown line-vl">
                            <a class="nav-link dropdown-toggle" href="#idAcerca" id="dropdown05" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
                                <strong> Acerca </strong>
                            </a>
                            <div class="dropdown-menu" id="idAcerca" aria-labelledby="dropdown05">
                                <!-- PRODUCTOD ACERCA DE -->
                                <div class="">
                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE0005">
                                        <i class="fa fa-map" aria-hidden="true"></i> Mapa de Sitio <br>
                                        <span class="small m-3"> Descripción de las opciones del Portal </span>
                                    </a>
                                </div>
                                <div class="">
                                    <a class="dropdown-item" href="/application/requerimiento/producto/RE0003">
                                        <i class="fa fa-history" aria-hidden="true"></i> Acerda de <br>
                                        <span class="small m-3"> Tareas recientes y actualizaciones </span>
                                    </a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>

                <!-- Formulario para la búsqueda en el portal -->
                <form class="form-inline ml-1 d-none d-lg-block" method="post" action="/application/index/busqueda">
                    <div class="input-group">
                        <input type="text" size="20" class="form-control rounded" placeholder="Buscar Producto" aria-label="producti" id="buscar" name="buscar" aria-describedby="basic-addon1">
                        <button class="btn btn-dark" type="submit" id="button-addon1">
                            <i class="fa fa-search"></i>
                        </button>
                        <input name="csrf" type="hidden" value="m75o14b9f0q65nlpp1ok8ph1mr">
                    </div>
                </form>

                <!-- Botón para el Login -->
                <a href="/application/usuario/loginUsuario" class="btn btn-info text-dark mx-3 text-light">
                    <small> Iniciar Sesión </small>
                </a>
            </nav>
        </div>
    </div>
</header>
   <section class="container-fluid">
            <div class="row mb-3">
                <div class="col-12">
                    <div class="card">
                        <div
                            class="card-header text-start bg-cabezera text-white align-content-start"
                            id="cabezera">
                           <img src="/img/ENANDES.png" class="float-right" style="width: 10%;" alt="Logo ENANDES">
                            <h3>
                                <img src="https://climatologia.meteochile.gob.cl/images/euroclima/sunPlantWiltSolid.svg"
                                     alt="icono sequia"
                                     class="iconosequia"
                                     style="width:50px;height:50px">
                                <span>Productos Monitor Sequía.</span>
                            </h3>
                            <h5>Datos e imágenes para la Región de <strong>Valparaíso</strong>.</h5>
                        </div>
                    </div>
                </div>
            </div>
   </section>

    
    <div class="container-fluid">
        <?= $this->content; ?>
    </div>
    
    <script src="https://climatologia.meteochile.gob.cl/js/bootstrap.min.js"></script>
    <script src="https://climatologia.meteochile.gob.cl/js/MegaNavbarBS5.js"></script>
    <script src="<?= $this->basePath('/js/leaflet/leaflet.js') ?>"></script>

    <script src="<?= $this->basePath('/js/menu.js') ?>"></script>
    <script src="<?= $this->basePath('/js/model.js') ?>"></script>
    <script src="<?= $this->basePath('/js/view.js') ?>"></script>
    <script src="<?= $this->basePath('/js/controller.js') ?>"></script>
    <script src="<?= $this->basePath('/js/main.js') ?>"></script>
    
    <?= $this->inlineScript() ?>
</body>
</html>
