<?php
// module/Application/view/application/partial/sequia-legend.phtml
// Leyenda de categorías de sequía reutilizable
?>
<div id="map-legend" class="legend d-inline-block">
    <table class="table-legend">
        <thead>
            <tr>
                <th scope="col">Categoría 1</th>
                <th scope="col">Categoría 2</th>
                <th scope="col">Categoría 3</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><span class="color-box" style="background:#d9d9d9;"></span> SS</td>
                <td><span class="color-box" style="background:#ffff00;"></span> D0</td>
                <td><span class="color-box" style="background:#fcd37f;"></span> D1</td>
            </tr>
            <tr>
                <td><span class="color-box" style="background:#ffaa00;"></span> D2</td>
                <td><span class="color-box" style="background:#EA2B00;"></span> D3</td>
                <td><span class="color-box" style="background:#801300;"></span> D4</td>
            </tr>
        </tbody>
    </table>
</div>
