<?php


$this->headTitle('Indice de Sequia - Región de Valparaíso');


$this->inlineScript()
    ->appendFile('https://climatologia.meteochile.gob.cl/js/bootstrap.min.js')
    ->appendFile('https://climatologia.meteochile.gob.cl/js/MegaNavbarBS5.js')

    ->appendFile($this->basePath('/js/menu.js'));
?>
<section class="container-fluid">
    <!-- Requerimiento : RE8013 -->
  
    <div class="row mb-3">
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <div class="card">
                        <div class="" id="container">
                            <div id="left">
                                <img src="https://climatologia.meteochile.gob.cl/images/euroclima/earth3355931640.jpg" alt=" Imagen no encontrada.">
                            </div>
                            <div id="right">
                                <img src="https://climatologia.meteochile.gob.cl/images/euroclima/cornfield4240209640.jpg" alt=" Imagen no encontrada.">
                            </div>
                        </div>
                        <div class="card-body">
                            <p class="card-text">El monitoreo de
                                sequía meteorológica en Chile, se ha
                                actualizado con el objetivo de
                                proporcionar un nuevo índice que
                                permite un
                                análisis más
                                detallado de la sequía en nuestro
                                país considerando no sólo la
                                precipitación
                                como fuente de información, sino que
                                debido a los significativos cambios
                                sobre
                                todo en la temperatura, es que se
                                hace necesario evaluar éste y otros
                                índices.
                            </p>
                        </div>
                    </div>
                    <br>
                    <div class="card ">
                        <div class="" id="container">
                            <div id="left">
                                <img src="https://climatologia.meteochile.gob.cl/images/euroclima/lake7407087640.jpg" alt=" Imagen no encontrada.">
                            </div>
                            <div id="right">
                                <img src="https://climatologia.meteochile.gob.cl/images/euroclima/erosion5621597640.jpg" alt=" Imagen no encontrada.">
                            </div>
                        </div>
                        <div class="card-body btn btn-light">
                            <a style="text-decoration: none; color: black;" href="https://climatologia.meteochile.gob.cl/application/requerimiento/producto/RE1029">
                                <div class="text-justify">
                                    <h5><strong>Mapa de Sequía
                                            "Índice combinado".</strong></h5>
                                </div>
                                <p class="card-text text-justify">
                                    El mapa de sequía es un índice
                                    combinado y ponderado que se
                                    construye con
                                    los índices estandarizados de
                                    temperatura,
                                    precipitación,
                                    evapotranspiración, vegetación
                                    normalizada, y humedad del
                                    suelo.<br><strong>"Haz clic aquí "</strong>
                                    para ir al producto.
                                </p>
                            </a>
                        </div>
                    </div>
                    <br>
                    <div class="card">
                        <div class="" id="container">
                            <div id="left">
                                <img src="https://climatologia.meteochile.gob.cl/images/euroclima/forest1072828640.jpg" alt=" Imagen no encontrada.">
                            </div>
                            <div id="right">
                                <img src="https://climatologia.meteochile.gob.cl/images/euroclima/water2208931640.jpg" alt=" Imagen no encontrada.">
                            </div>
                        </div>
                        <div class="card-body btn-light">
                            <a style="text-decoration: none; color: black;" href="https://climatologia.meteochile.gob.cl/application/historico/areaAfectadaSequia">
                                <div class="">
                                    <h5><strong>Serie de tiempo del
                                            porcentaje de
                                            afectación</strong></h5>
                                </div>
                                <p class="card-text text-justify">
                                    Este producto muestra la serie
                                    de tiempo a nivel mensual el
                                    porcentaje de
                                    sequia nacional en diferentes
                                    categorías.
                                    <br><strong>"Haz clic aquí "</strong>
                                    para ir al producto.
                                </p>
                            </a>
                        </div>
                    </div>
                    <br>
                    <div class="card">
                        <div class="" id="container">
                            <div id="left">
                                <img src="https://climatologia.meteochile.gob.cl/images/euroclima/desert2497135640.jpg" alt=" Imagen no encontrada.">
                            </div>
                            <div id="right">
                                <img src="https://climatologia.meteochile.gob.cl/images/euroclima/earth3545203640.jpg" alt=" Imagen no encontrada.">
                            </div>
                        </div>
                        <div class="card-body btn-light">
                            <a style="text-decoration: none; color: black;" href="https://climatologia.meteochile.gob.cl/application/requerimiento/producto/RE1030">
                                <div class="">
                                    <h5><strong>Porcentaje de área
                                            afectada por la
                                            sequía.</strong></h5>
                                </div>
                                <p class="card-text text-justify">
                                    En el siguiente enlace podrá
                                    consultar los porcentajes de
                                    área de las
                                    unidades territoriales de Chile
                                    que se encuentran bajo los
                                    diferentes grados
                                    de intensidad de sequía
                                    calculados a partir de las
                                    salidas del monitor de sequías a
                                    un mes para la
                                    fecha
                                    indicada.<br><strong>"Haz clic aquí "</strong>
                                    para ir al producto.
                                </p>
                            </a>
                        </div>
                    </div>
                    <br>

                   
                </div>
            </div>
        </div>
        <!-- imagenes -->
        <div class="col-lg-7">
            <div class="card">
                <div class="card-header text-start p-3 mb-2 bg-info text-white">
                    <h4> Imagen actual intensidad de la sequía e
                        índice estandarizado de precipitación. <i class="fa fa-picture-o float-right" aria-hidden="true"></i></h4>
                    <h4>
                    </h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 d-flex justify-content-center">
                            <div class="my-auto">
                                <img class="slides img-fluid img-thumbnail" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/mon/png/2025_03_01.png" alt=" Imagen no encontrada.">
                                <img class="slides img-fluid img-thumbnail slides-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/mon/png/2025_03_03.png" alt=" Imagen no encontrada.">
                                <img class="slides img-fluid img-thumbnail slides-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/mon/png/2025_03_06.png" alt=" Imagen no encontrada.">
                                <img class="slides img-fluid img-thumbnail slides-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/mon/png/2025_03_09.png" alt=" Imagen no encontrada.">
                                <img class="slides img-fluid img-thumbnail slides-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/mon/png/2025_03_12.png" alt=" Imagen no encontrada.">
                                <img class="slides img-fluid img-thumbnail slides-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/mon/png/2025_03_24.png" alt=" Imagen no encontrada.">
                                <img class="slides img-fluid img-thumbnail slides-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/mon/png/2025_03_48.png" alt=" Imagen no encontrada.">
                            </div>
                        </div>
                        <div class="col-md-6 d-flex justify-content-center">
                            <div class="my-auto">
                                <img class="slides2 img-fluid img-thumbnail" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/spi/png/2025_03_01_spi.png" alt=" Imagen no encontrada.">
                                <img class="slides2 img-fluid img-thumbnail slides2-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/spi/png/2025_03_03_spi.png" alt=" Imagen no encontrada.">
                                <img class="slides2 img-fluid img-thumbnail slides2-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/spi/png/2025_03_06_spi.png" alt=" Imagen no encontrada.">
                                <img class="slides2 img-fluid img-thumbnail slides2-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/spi/png/2025_03_09_spi.png" alt=" Imagen no encontrada.">
                                <img class="slides2 img-fluid img-thumbnail slides2-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/spi/png/2025_03_12_spi.png" alt=" Imagen no encontrada.">
                                <img class="slides2 img-fluid img-thumbnail slides2-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/spi/png/2025_03_24_spi.png" alt=" Imagen no encontrada.">
                                <img class="slides2 img-fluid img-thumbnail slides2-hidden" src="https://climatologia.meteochile.gob.cl/images/productosMonitor/indices/spi/png/2025_03_48_spi.png" alt=" Imagen no encontrada.">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <div class="card fluid">
                <div class="card-header p-3 mb-2 bg-info text-white">
                    <h5 class="card-title">Boletín de sequía.<i class="fa fa-file-pdf-o float-right" aria-hidden="true"></i></h5>
                </div>
                <div class="card-body btn-light">
                    <a style="text-decoration: none; color: black;" href="https://climatologia.meteochile.gob.cl/application/publicaciones/boletinDeSequias">
                        <p class="card-text text-justify">El Boletín
                            de Sequía proporciona un monitoreo
                            mensual
                            de la sequía que experimenta nuestro
                            país,
                            a través del Índice de Precipitación
                            Estandarizado (IPE; Standardized
                            Precipitation
                            Index, SPI) e Índice Combinado (Índices
                            de precipitación,
                            temperatura, humedad del suelo,
                            evapotranspiración y
                            vegetación).<br><strong>"Haz
                                clic aquí "</strong> para ir al
                            producto.
                        </p>
                    </a>
                </div>
            </div>
            <br>
             <div class="card fluid">
                    <div class="card-header p-3 mb-2 bg-info text-white">
                        <h5 class="card-title">Monitor de Sequia para región de Valparaíso</h5>
                    </div>
                    <div class="card-body btn-light">
                        <a style="text-decoration: none; color: black;" href="<?= $this->url('indice-combinado') ?>">
                            <p class="card-text text-justify">El Boletín
                                de Sequía proporciona un monitoreo
                                mensual
                                de la sequía que experimenta nuestro
                                país,
                                a través del Índice de Precipitación
                                Estandarizado (IPE; Standardized
                                Precipitation
                                Index, SPI) e Índice Combinado (Índices
                                de precipitación,
                                temperatura, humedad del suelo,
                                evapotranspiración y
                                vegetación).<br><strong>"Haz
                                    clic aquí "</strong> para ir al
                                producto.
                            </p>
                        </a>
                    </div>
            </div>
            
        </div>
    </div>
    <!-- NUMERO DE REQUERIMIENTO Y BARRA DE PIE DE PAGINA -->
    <div class="row">
        <div class="col-12 mt-2">
            <h5 class="text-end text-requerimiento">Informe generado
                el 02-05-2025 17:05</h5>
            <h5>
                <span class="text-requerimiento" id="numeroRequerimiento">
                    Requerimiento: RE8013 </span>
            </h5>
        </div>
    </div>

    <!-- script para cambiar imagenes -->
    <script>
        addEventListener("load", () => {
            var index = 0;
            const slides = document.querySelectorAll(".slides");
            const classHide = "slides-hidden",
                count = slides.length;
            nextSlide();

            function nextSlide() {
                slides[(index++) % count].classList.add(classHide);
                slides[index % count].classList.remove(classHide);
                setTimeout(nextSlide, 3000);
            }
        });
        addEventListener("load", () => {
            var index = 0;
            const slides = document.querySelectorAll(".slides2");
            const classHide = "slides2-hidden",
                count = slides.length;
            nextSlide();

            function nextSlide() {
                slides[(index++) % count].classList.add(classHide);
                slides[index % count].classList.remove(classHide);
                setTimeout(nextSlide, 3000);
            }
        });
    </script>

    <style>
        .iconosequia {
            filter: invert(100%) sepia(0%) saturate(7500%) hue-rotate(57deg) brightness(103%) contrast(103%);
        }

        .slides {
            width: auto;
            height: 600px;
            max-height: 700px;
        }

        .slides-hidden {
            display: none;
        }

        .slides2 {
            width: auto;
            height: 600px;
            max-height: 700px;
        }

        .slides2-hidden {
            display: none;
        }

        #container {
            position: relative;
            width: 100%;
            height: 100px;
            overflow: hidden;
        }

        #left,
        #right {
            position: absolute;
            width: calc(50% + 100px);
            height: 300px;
            transform: skew(-20deg, 0deg);
            overflow: hidden;
        }

        #left img,
        #right img {
            position: absolute;
            width: 100%;
            height: 100%;
            object-fit: cover;
            transform: skew(20deg, 0deg);
        }

        .content {
            position: absolute;
            top: 50%;
            left: calc(50% + 50px);
            background-color: rgba(255, 255, 255, .5);
            transform: skew(20deg, 0deg) translate(-50%, -50%);
        }

        #right .content {
            left: 50%;
            right: 50px;
        }

        #left,
        #right img {
            left: -100px;
        }

        #right,
        #left img {
            right: -100px;
        }

        .Euro_Ciifen {
            width: 20%;
        }
    </style>
</section>